M48
; DRILL file {KiCad 7.0.6} date Fri Sep  1 11:13:43 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-09-01T11:13:43+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
%
G90
G05
T1
X174.005Y-92.825
X174.005Y-97.675
T2
X177.035Y-92.525
X177.035Y-97.975
T0
M30
